### ISSUE TITLE
(Random?) panic when adding torrent from magnet link

### ISSUE THREAD

**Issue by steinuil** [Luminarys/synapse#123] opened 2018-08-14 22:48 UTC
I added a torrent through receptor using a magnet link and specifying the download folder, but otherwise leaving the settings to default. synapse immediately panicked and crashed with this message:

```
thread 'trk' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
08/15/18 00:24:25 [synapse::control:146] E: crashed thread detected, terminating!
08/15/18 00:24:25 [synapse::init:41] E: Unclean shutdown detected, terminating
```

I tried adding the torrent the same way with RUST_BACKTRACE set after starting it up again but couldn't reproduce the panic.

I should also add that synapse doesn't seem to like the tracker the torrent was using, since it spit out this later:
```
08/15/18 00:24:45 [synapse::tracker::dht:53] I: Attempting DHT bootstrap!
08/15/18 00:25:51 [synapse::torrent:573] E: Failed to query tracker http://nyaa.tracker.wf:7777/announce: invalid tracker response: Invalid BEncoded response!
```

I'm on Fedora 27, and compiled synapse with rustc 1.27.0. Sorry for the scarcity of info, I really don't know where to even begin debugging this. Tell me if you need anything more.

**Comment by Luminarys** [comment] 2018-08-16 15:25
There have been some issues with the nyaa tracker in the past, if it's still not working I'll take a look into it. As for the panic, it appears to be caused by Rust's read_exact function which appears twice in the code base, and in this case likely the bencode handler. I'll give the code a review and I'd appreciate it if you could link the magnet in question.

**Comment by Luminarys** [comment] 2018-08-16 15:33
Ok here's my best guess, the tracker gave an incomplete response, causing a panic in https://github.com/Luminarys/synapse/blob/5222ab92e61b43903ed53daf006c9f4f58e872c3/src/tracker/mod.rs#L396
That code will need to be hardened.

**Comment by Luminarys** [comment] 2018-08-16 15:35
I think in general a review of every single unwrap and changing them to expect with exact reasonings for why they should never fail is something to be done.

**Comment by steinuil** [comment] 2018-08-16 16:25
I'm pretty confident the magnet link was this.
```
magnet:?xt=urn:btih:4793d9142c2cddcbbc06e0b33bbe270ecf0d4c10&dn=%5BHorribleSubs%5D%20Chuukan%20Kanriroku%20Tonegawa%20-%2007%20%5B720p%5D.mkv&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce
```

**Comment by steinuil** [comment] 2018-08-16 16:39
By the way, I'm also noticing that only the first tracker gets added to the torrent. I'm guessing the url library is overzealous in its adherence to the spec and only considers the first `tr` in the query string as valid and discards the rest. Should I open a separate bug for this?

**Comment by Luminarys** [comment] 2018-08-17 01:54
Yep, go ahead.

**Comment by Luminarys** [comment] 2018-10-09 04:53
This specific bug should be fixed now, closing.

**Closed as completed by Luminarys** 2018-10-09 04:53 UTC
Labels: bug, synapse
